r01/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, shallow: true do
    resources :posts
  end

  namespace :api do
    namespace :v1 do
      resources :user_avatars, only: :create
      resource :presigned_url, only: :show
      resources :tasks,
                defaults: { format: :json },
                only: %i[index create show update destroy]
    end
  end
end

r01/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

r01/app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user

  attribute :image_path

  def set_image!
    move_to(image_path, "#{carrierwave_store_dir('image')}/#{image}")
    self.image = image
    save!
  end

  def image_url
    "http://localhost:4566/#{Settings.aws.s3.bucket}/#{carrierwave_store_dir('image')}/#{image}"
  end

  private

  def carrierwave_store_dir(mounted_as)
    "uploads/post/#{mounted_as}/#{id}"
  end

  def move_to(from_path, to_path)
    from_obj = bucket.object(from_path)
    to_obj = bucket.object(to_path)
    from_obj.copy_to(to_obj)
    from_obj.delete
  end

  def bucket
    @bucket ||=
      Aws::S3::Bucket.new(
        Settings.aws.s3.bucket,
        region: Settings.aws.region,
        endpoint: 'http://localstack:4566',
        force_path_style: true
      )
  end
end

r01/app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validates :title, presence: true
end

r01/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one :avatar, class_name: 'UserAvatar', dependent: :destroy
  has_many :posts, dependent: :destroy

  attribute :avatar_id, :integer

  def avatar_id=(avatar_id)
    super(avatar_id)
    self.avatar = UserAvatar.find_by(id: avatar_id)
  end

  def avatar_id
    avatar&.id
  end
end

r01/app/models/user_avatar.rb
# frozen_string_literal: true

class UserAvatar < ApplicationRecord
  belongs_to :user, optional: true

  mount_uploader :image, AvatarUploader
end

r01/app/controllers/api/v1/presigned_urls_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PresignedUrlsController < ApplicationController
      def show
        path = "#{base_dir}/#{params[:filename]}"
        presigned_url = get_presigned_url(path, content_type: params[:content_type])
        render json: { url: presigned_url, path: }
      end

      private

      def get_presigned_url(object_key, **attrs)
        url = bucket.object(object_key).presigned_url(:put, attrs)
        URI(url)
      end

      def bucket
        @bucket ||=
          Aws::S3::Bucket.new(
            Settings.aws.s3.bucket,
            region: Settings.aws.region,
            endpoint: 'http://localhost:4566',
            force_path_style: true
          )
      end

      def base_dir
        "tmp_uploads/#{uuid}"
      end

      def uuid
        SecureRandom.uuid
      end
    end
  end
end

r01/app/controllers/api/v1/tasks_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class TasksController < ApplicationController
      skip_before_action :verify_authenticity_token
      def index
        @tasks = Task.all
      end

      def create
        @task = Task.new(task_params)
        if @task.invalid?
          return render json: { messages: @task.errors.full_messages },
                        status: :unprocessable_entity
        end

        @task.save!
      end

      def show
        @task = Task.find(params[:id])
      end

      def update
        @task = Task.find(params[:id])
        @task.attributes = task_params
        if @task.invalid?
          return render json: { messages: @task.errors.full_messages },
                        status: :unprocessable_entity
        end

        @task.save!
      end

      def destroy
        @task = Task.find(params[:id])
        @task.destroy!
      end

      private

      def task_params
        params.require(:task).permit(:title, :content)
      end
    end
  end
end

r01/app/controllers/api/v1/user_avatars_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class UserAvatarsController < ApplicationController
      def create
        user_avatar = UserAvatar.new(user_avatar_params)
        if user_avatar.invalid?
          return render json: { messages: user_avatar.errors.full_messages }, status: :unprocessable_entity
        end

        user_avatar.save!
        render json: { user_avatar_id: user_avatar.id, user_avatar_url: user_avatar.image.url }
      end

      private

      def user_avatar_params
        params.require(:user_avatar).permit(:image)
      end
    end
  end
end

r01/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

r01/app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_user, only: %i[index new create]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = @user.posts
  end

  def new
    @post = @user.posts.build
  end

  def create
    @post = @user.posts.build(post_params)
    return render :new if @post.invalid?

    ApplicationRecord.transaction do
      @post.save!
      @post.set_image!
    end
    redirect_to post_path(@post)
  end

  def show; end

  def edit; end

  def update
    @post.attributes = post_params
    return render :edit if @post.invalid?

    ApplicationRecord.transaction do
      @post.save!
      @post.set_image!
    end
    redirect_to post_path(@post)
  end

  def destroy
    @user = @post.user
    @post.destroy!
    redirect_to user_posts_path(@user)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content, :image, :image_path)
  end
end

r01/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
#    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :avatar_id)
  end
end

r01/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

r01/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

r01/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

r01/app/views/posts/_form.html.erb
<%= form_with(model: post, url: @post.new_record? ? user_posts_path(@user) : post_path(@post), data: { controller: 'post-form' }) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= label_tag :tmp_image, '', style: "display: block" %>
    <%= file_field_tag :tmp_image, data: { action: 'change->post-form#changeImage' } %>
  </div>

  <div>
    <%= form.hidden_field :image, data: { post_form_target: 'imageName' } %>
    <%= form.hidden_field :image_path, data: { post_form_target: 'imagePath' } %>
    <%= form.submit %>
  </div>
<% end %>

r01/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>Image:</strong>
    <% if post.image.present? %>
      <%= image_tag post.image_url %>
    <% end %>
  </p>
</div>

r01/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", user_posts_path(@post.user) %>
</div>

r01/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_user_post_path(@user) %>

r01/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", user_posts_path(@user) %>
</div>

r01/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", user_posts_path(@post.user) %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

r01/app/views/users/_form.html.erb
<%= form_with(model: user,  data: { controller: 'user' }) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <label>
      Avatar
      <input type="file" data-action="change->user#changeAvatar" />
    </label>
    <div data-user-target="avatarImageArea"></div>
  </div>

  <%= form.hidden_field :avatar_id, data: { user_target: 'avatarIdField' } %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

r01/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>
  <p>
    <strong>Avatar:</strong>
    <% if user.avatar.present? %>
      <%= image_tag user.avatar.image.url %>
    <% end %>
  </p>
</div>

r01/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

r01/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

r01/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

r01/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>